// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Url struct {
	UrlID       int32
	OriginalUrl string
	ShortUrl    string
	UserID      int32
	CreatedAt   sql.NullTime
}

type User struct {
	UserID int32
	Email  string
}
